### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'seeders')

### ISSUE THREAD

**Issue by hyoretsu** [aymene69/stremio-jackett#10]
```
Series request. ID: tt7326322 Name: The Ancient Magus' Bride Season: 02 Episode: 01
Searching on Jackett...
Will return Torrents.
Getting torrent info...
Torrent info: [Yameii] The Ancient Magus' Bride - S02E01 [English Dub] [CR WEB-DL 1080p] [2B1B4AF9] (Mahoutsukai no Yome S2 | Season 2)
TypeError: Cannot set properties of undefined (setting 'seeders')
    at Object.jackettSearch (file:///C:/Users/hyore/stremio-jackett/jackett.js:149:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/hyore/stremio-jackett/index.js:69:33
```

**Comment by hyoretsu** [comment]
![image](https://github.com/aymene69/stremio-jackett/assets/20804322/6d0ad6f4-42f3-4ee2-93a1-bf58ea4077f6)

**Comment by aymene69** [comment]
Is the download link a magnet ?

**Comment by hyoretsu** [comment]
Yes, this is "items". The problem is that getTorrentInfo() is returning undefined
```
[
  {
    title: "[Yameii] The Ancient Magus' Bride - S02E02 [English Dub] [CR WEB-DL 1080p] [38CFED27] (Mahoutsukai no Yome S2 | Season 2)",
    size: '1503238528',
    link: 'magnet:?xt=urn:btih:71d0f729d80330fafa2485210b9661ffe97c45c2&dn=%5BYameii%5D%20The%20Ancient%20Magus%27%20Bride%20-%20S02E02%20%5BEnglish%20Dub%5D%20%5BCR%20WEB-DL%201080p%5D%20%5B38CFED27%5D%20%28Mahoutsukai%20no%20Yome%20S2%20%7C%20Season%202%29&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce',
    seeders: '20'
  },
  {
    title: "[Yameii] The Ancient Magus' Bride - S02E02 [English Dub] [CR WEB-DL 1080p] [38CFED27] (Mahoutsukai no Yome S2 | Season 2)",
    size: '1503238528',
    link: 'magnet:?xt=urn:btih:71d0f729d80330fafa2485210b9661ffe97c45c2&dn=%5BYameii%5D%20The%20Ancient%20Magus%27%20Bride%20-%20S02E02%20%5BEnglish%20Dub%5D%20%5BCR%20WEB-DL%201080p%5D%20%5B38CFED27%5D%20%28Mahoutsukai%20no%20Yome%20S2%20%7C%20Season%202%29&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce',
    seeders: '20'
  },
  {
    title: "The Ancient Magus' Bride S02E02 VOSTFR 1080p WEB x264 AAC -Tsundere-Raws (CR) (Mahoutsukai no Yome Season 2)",
    size: '1503238528',
    link: 'magnet:?xt=urn:btih:bf4ae05c42e95398d086d25b6a916ff368e17034&dn=The%20Ancient%20Magus%27%20Bride%20S02E02%20VOSTFR%201080p%20WEB%20x264%20AAC%20-Tsundere-Raws%20%28CR%29%20%28Mahoutsukai%20no%20Yome%20Season%202%29&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce',
    seeders: '15'
  },
  {
    title: "The Ancient Magus' Bride S02E02 VOSTFR 1080p WEB x264 AAC -Tsundere-Raws (CR) (Mahoutsukai no Yome Season 2)",
    size: '1503238528',
    link: 'magnet:?xt=urn:btih:bf4ae05c42e95398d086d25b6a916ff368e17034&dn=The%20Ancient%20Magus%27%20Bride%20S02E02%20VOSTFR%201080p%20WEB%20x264%20AAC%20-Tsundere-Raws%20%28CR%29%20%28Mahoutsukai%20no%20Yome%20Season%202%29&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce',
    seeders: '15'
  },
  {
    title: "[Anime Time] Mahoutsukai no Yome S02E02 [1080p][HEVC 10bit x265][AAC][Multi Sub] [Weekly] (The Ancient Magus' Bride Season 2)",
    size: '288777824',
    link: 'magnet:?xt=urn:btih:f1be94e0fa17ec09ef7127fe79e6dba28d1994c6&dn=%5BAnime%20Time%5D%20Mahoutsukai%20no%20Yome%20S02E02%20%5B1080p%5D%5BHEVC%2010bit%20x265%5D%5BAAC%5D%5BMulti%20Sub%5D%20%5BWeekly%5D%20%28The%20Ancient%20Magus%27%20Bride%20Season%202%29&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce',
    seeders: '13'
  },
  {
    title: "[Anime Time] Mahoutsukai no Yome S02E02 [1080p][HEVC 10bit x265][AAC][Multi Sub] [Weekly] (The Ancient Magus' Bride Season 2)",
    size: '288777824',
    link: 'magnet:?xt=urn:btih:f1be94e0fa17ec09ef7127fe79e6dba28d1994c6&dn=%5BAnime%20Time%5D%20Mahoutsukai%20no%20Yome%20S02E02%20%5B1080p%5D%5BHEVC%2010bit%20x265%5D%5BAAC%5D%5BMulti%20Sub%5D%20%5BWeekly%5D%20%28The%20Ancient%20Magus%27%20Bride%20Season%202%29&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce',
    seeders: '13'
  },
  {
    title: "The Ancient Magus' Bride S02E02 VOSTFR 720p WEB x264 AAC -Tsundere-Raws (CR) (Mahoutsukai no Yome Season 2)",
    size: '748368704',
    link: 'magnet:?xt=urn:btih:359e8f1c220b8351c743cd36539ac3080fea42f4&dn=The%20Ancient%20Magus%27%20Bride%20S02E02%20VOSTFR%20720p%20WEB%20x264%20AAC%20-Tsundere-Raws%20%28CR%29%20%28Mahoutsukai%20no%20Yome%20Season%202%29&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce',
    seeders: '9'
  },
  {
    title: "The Ancient Magus' Bride S02E02 VOSTFR 720p WEB x264 AAC -Tsundere-Raws (CR) (Mahoutsukai no Yome Season 2)",
    size: '748368704',
    link: 'magnet:?xt=urn:btih:359e8f1c220b8351c743cd36539ac3080fea42f4&dn=The%20Ancient%20Magus%27%20Bride%20S02E02%20VOSTFR%20720p%20WEB%20x264%20AAC%20-Tsundere-Raws%20%28CR%29%20%28Mahoutsukai%20no%20Yome%20Season%202%29&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce',
    seeders: '9'
  },
  {
    title: 'The Ancient Magus Bride S02E02 1080p WEB H264-SENPAI',
    size: '1471026304',
    link: 'magnet:?xt=urn:btih:d3adb27d36e93eff0b9c7dae9bf4592036d97bdd&dn=the.ancient.magus.bride.s02e02.1080p.web.h264-senpai%5Beztv.re%5D.mkv%5Beztvx.to%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce',
    seeders: '5'
  },
  {
    title: "[Yameii] The Ancient Magus' Bride - S02E02 [English Dub] [CR WEB-DL 720p] [7A780940] (Mahoutsukai no Yome S2 | Season 2)",
    size: '745747264',
    link: 'magnet:?xt=urn:btih:56905a882e72ad7184f74f773316e3043896f230&dn=%5BYameii%5D%20The%20Ancient%20Magus%27%20Bride%20-%20S02E02%20%5BEnglish%20Dub%5D%20%5BCR%20WEB-DL%20720p%5D%20%5B7A780940%5D%20%28Mahoutsukai%20no%20Yome%20S2%20%7C%20Season%202%29&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce',
    seeders: '3'
  },
  {
    title: "[Yameii] The Ancient Magus' Bride - S02E02 [English Dub] [CR WEB-DL 720p] [7A780940] (Mahoutsukai no Yome S2 | Season 2)",
    size: '745747264',
    link: 'magnet:?xt=urn:btih:56905a882e72ad7184f74f773316e3043896f230&dn=%5BYameii%5D%20The%20Ancient%20Magus%27%20Bride%20-%20S02E02%20%5BEnglish%20Dub%5D%20%5BCR%20WEB-DL%20720p%5D%20%5B7A780940%5D%20%28Mahoutsukai%20no%20Yome%20S2%20%7C%20Season%202%29&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce',
    seeders: '3'
  },
  {
    title: 'The Ancient Magus Bride S02E02 1080p WEB H264-SENPAI',
    size: '1471026304',
    link: 'magnet:?xt=urn:btih:D3ADB27D36E93EFF0B9C7DAE9BF4592036D97BDD&dn=The+Ancient+Magus+Bride+S02E02+1080p+WEB+H264-SENPAI&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=https%3A%2F%2Fopentracker.i2p.rocks%3A443%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce',
    seeders: '1'
  },
  {
    title: 'The Ancient Magus Bride S02E02 1080p HEVC x265-MeGusta',
    size: '136493136',
    link: 'magnet:?xt=urn:btih:0D12356EFE132A228564F1C8B2CEF5A53E782636&dn=The+Ancient+Magus+Bride+S02E02+1080p+HEVC+x265-MeGusta&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=https%3A%2F%2Fopentracker.i2p.rocks%3A443%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce',
    seeders: '1'
  },
  {
    title: 'The Ancient Magus Bride S02E02 1080p HEVC x265-MeGusta',
    size: '136314880',
    link: 'magnet:?xt=urn:btih:0d12356efe132a228564f1c8b2cef5a53e782636&dn=The.Ancient.Magus.Bride.S02E02.1080p.HEVC.x265-MeGusta%5Beztv.re%5D.mkv%5Beztvx.to%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce',
    seeders: '1'
  },
  {
    title: 'The Ancient Magus Bride S02E02 DUBBED 720p WEB H264-SKYANiME',
    size: '745537536',
    link: 'magnet:?xt=urn:btih:fbdaad820aefef1aace3eb01aab2354d8098f4a1&dn=the.ancient.magus.bride.s02e02.dubbed.720p.web.h264-skyanime%5Beztv.re%5D.mkv%5Beztvx.to%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce',
    seeders: '0'
  },
  {
    title: 'The Ancient Magus Bride S02E02 720p WEB H264-SKYANiME',
    size: '747634688',
    link: 'magnet:?xt=urn:btih:3d582d746686214172f2f7318f764d050e654539&dn=the.ancient.magus.bride.s02e02.720p.web.h264-skyanime%5Beztv.re%5D.mkv%5Beztvx.to%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce',
    seeders: '0'
  },
  {
    title: 'The Ancient Magus Bride S02E02 XviD-AFG',
    size: '219152384',
    link: 'magnet:?xt=urn:btih:12d63137b3119ecc891aebd125fe4af634cc9c1e&dn=The.Ancient.Magus.Bride.S02E02.XviD-AFG%5Beztv.re%5D.avi%5Beztvx.to%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce',
    seeders: '0'
  },
  {
    title: 'The Ancient Magus Bride S02E02 XviD-AFG',
    size: '219131408',
    link: 'magnet:?xt=urn:btih:12D63137B3119ECC891AEBD125FE4AF634CC9C1E&dn=The+Ancient+Magus+Bride+S02E02+XviD-AFG&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=https%3A%2F%2Fopentracker.i2p.rocks%3A443%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce',
    seeders: '0'
  },
  {
    title: 'The Ancient Magus Bride S02E02 XviD-AFG',
    size: '220018704',
    link: 'magnet:?xt=urn:btih:12E89E95BE677A4FDF13D7D42CD5C51B8F861D93&dn=The+Ancient+Magus+Bride+S02E02+XviD-AFG&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=https%3A%2F%2Fopentracker.i2p.rocks%3A443%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce',
    seeders: '0'
  },
  {
    title: 'The Ancient Magus Bride S02E02 720p WEB H264-SKYANiME',
    size: '748148480',
    link: 'magnet:?xt=urn:btih:3D582D746686214172F2F7318F764D050E654539&dn=The+Ancient+Magus+Bride+S02E02+720p+WEB+H264-SKYANiME&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=https%3A%2F%2Fopentracker.i2p.rocks%3A443%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce',
    seeders: '0'
  },
  {
    title: 'The Ancient Magus Bride S02E02 DUBBED 720p WEB H264-SKYANiME',
    size: '745763904',
    link: 'magnet:?xt=urn:btih:FBDAAD820AEFEF1AACE3EB01AAB2354D8098F4A1&dn=The+Ancient+Magus+Bride+S02E02+DUBBED+720p+WEB+H264-SKYANiME&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=https%3A%2F%2Fopentracker.i2p.rocks%3A443%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce',
    seeders: '0'
  }
]
```

**Comment by aymene69** [comment]
my function isn't supporting yet magnets. Can you give me the tracker so I can make a fix for magnets ? Thanks

**Comment by hyoretsu** [comment]
I think what you're asking for is this, right?
![image](https://github.com/aymene69/stremio-jackett/assets/20804322/9946067f-a016-46ce-95c7-cb4214de7ff1)

**Comment by hyoretsu** [comment]
Managed to make it work.
![image](https://github.com/aymene69/stremio-jackett/assets/20804322/9e106cc6-6c28-46c6-a1ba-ff25c72e8463)
Btw, the Jackett server only queries stuff right? It isn't the one doing the downloads

**Comment by aymene69** [comment]
exactly. jackett only fetches download links

**Comment by hyoretsu** [comment]
Thanks for the confirmation. I'm using a cheap EC2 instance, so the lighter the better haha.

I'm looking into how to get the japanese title for anime, since as of now we only get few results with fewer seeders using the English title.

**Comment by aymene69** [comment]
merged your pr. Thanks a lot! I knew this was an issue but i didnt think it was on such a large amounts of trackers!

yeah, i made it very light because of this. at first, I wasnt comfortable with nodejs so i made it half nodejs half python... poor performances
