### ISSUE TITLE
TypeError: node-fetch cannot load [object Request]. URL scheme "magnet" is not supported.

### ISSUE THREAD

**Issue by hyoretsu** [aymene69/stremio-jackett#14]
Magnet links now work, but I actually receive the following error for TheRARBG, which asks me to download in Jackett's UI so I presume it isn't a magnet. For reference the query is `Frieren: Beyond Journey's End S01E09`
```
0|stremio-jackett  | TypeError: node-fetch cannot load [object Request]. URL scheme "magnet" is not supported.
0|stremio-jackett  |     at file:///srv/stremio-jackett/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:54:10
0|stremio-jackett  |     at new Promise (<anonymous>)
0|stremio-jackett  |     at fetch (file:///srv/stremio-jackett/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:49:9)
0|stremio-jackett  |     at ClientRequest.<anonymous> (file:///srv/stremio-jackett/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:236:15)
0|stremio-jackett  |     at ClientRequest.emit (node:events:530:35)
0|stremio-jackett  |     at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
0|stremio-jackett  |     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
0|stremio-jackett  |     at Socket.socketOnData (node:_http_client:535:22)
0|stremio-jackett  |     at Socket.emit (node:events:530:35)
0|stremio-jackett  |     at addChunk (node:internal/streams/readable:559:12)
```

**Comment by hyoretsu** [comment]
It seems to be an URL which resolves to a magnet. Might need to add a special treatment for these kinds of indexers.

**Comment by aymene69** [comment]
Yes. The URL changes the header to the magnet one on certain links
