### ISSUE TITLE
[Bug] ASGI 'lifespan' protocol appears unsupported

### ISSUE THREAD

**Issue by 9acca9** [aymene69/stremio-jackett#159]
Thanks for the updates!

I found this:

```
    ~/stremio-jackett/source    main  python3 -m uvicorn main:app --reload --port 3000       ✔  1m 58s   panchines@manjaro 
INFO:     Will watch for changes in these directories: ['/home/panchines/stremio-jackett/source']
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     Started reloader process [857432] using StatReload
[04-07 19:50:38] p857434 {/home/panchines/stremio-jackett/source/main.py:117} INFO - Started Jackett Addon
INFO:     Started server process [857434]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
```

I make this to see the error (following this https://stackoverflow.com/questions/64512286/asgi-lifespan-protocol-appears-unsupported):

```
   ~/stremio-jackett/source    main  python3 -m uvicorn main:app --reload --lifespan on --port 3000
INFO:     Will watch for changes in these directories: ['/home/panchines/stremio-jackett/source']
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     Started reloader process [857391] using StatReload
[04-07 19:48:35] p857393 {/home/panchines/stremio-jackett/source/main.py:117} INFO - Started Jackett Addon
INFO:     Started server process [857393]
INFO:     Waiting for application startup.
ERROR:    Exception in 'lifespan' protocol
Traceback (most recent call last):
  File "/home/panchines/.local/lib/python3.11/site-packages/uvicorn/lifespan/on.py", line 86, in main
    await app(scope, self.receive, self.send)
  File "/home/panchines/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/panchines/.local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/panchines/.local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/panchines/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/home/panchines/stremio-jackett/source/main.py", line 51, in __call__
    request = Request(scope, receive)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/panchines/.local/lib/python3.11/site-packages/starlette/requests.py", line 205, in __init__
    super().__init__(scope)
  File "/home/panchines/.local/lib/python3.11/site-packages/starlette/requests.py", line 72, in __init__
    assert scope["type"] in ("http", "websocket")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
ERROR:    Application startup failed. Exiting.
```

Thanks.

**Comment by aymene69** [comment]
This is a FastAPI issue, not a Stremio-Jackett one
