### ISSUE TITLE
Various errors when running?

### ISSUE THREAD

**Issue by mckenna654** [aymene69/stremio-jackett#19]
Stremio-jackett logs
![image](https://github.com/aymene69/stremio-jackett/assets/10954027/e02e8d88-ed8a-4c65-bba1-5549e262dd0b)

Jackett logs
![image](https://github.com/aymene69/stremio-jackett/assets/10954027/2be59099-0b4e-49e2-936d-b895209d0d77)

Hi, I'm running Jackett and Stremio-Jackett which are both publicly accessible through a reverse proxy. 

Any idea what these errors could be? On the stremio-jackett config page I've stated https://jackett.mydomain.com as the URL which is accessible

**Comment by aymene69** [comment]
Are you using All-debrid?

**Comment by mckenna654** [comment]
> Are you using All-debrid?

Real Debrid.

**Comment by aymene69** [comment]
try the new version and let me know

**Comment by mckenna654** [comment]
> try the new version and let me know

Docker says I have the latest version
<img width="1198" alt="image" src="https://github.com/aymene69/stremio-jackett/assets/10954027/3745be48-38b9-4fb2-a894-3a15d0804e8d">

![image](https://github.com/aymene69/stremio-jackett/assets/10954027/bfacf25b-992a-4f59-862d-6c77fb33c81d)

**Comment by mckenna654** [comment]
Can I just clarify something?
So because I'm unable to host Stremio-Jackett on 127.0.0.1 or localhost, stremio requires me to host it with https. I've setup a reverse proxy and can access it externally via https://stremio-jackett.mydomain.com

Would this mean when I'm filling out the config I would also need to put the public domain of Jackett being https://jackett.mydomain.com or can I just use the local IP of http://192.168.0.168:9117?

They're on the same local network

**Comment by aymene69** [comment]
Show the addon logs please

**Comment by mckenna654** [comment]
> Show the addon logs please

```
text  error  warn  system  array  login  

    at async jackettSearch (file:///app/src/jackett/index.js:31:15)
    at async file:///app/src/routes.js:54:24 {
  [cause]: TypeError: Invalid URL
      at new URL (node:internal/url:787:36)
      at new Request (node:internal/deps/undici/undici:5943:25)
      at fetch (node:internal/deps/undici/undici:10221:25)
      at Object.fetch (node:internal/deps/undici/undici:12441:10)
      at fetch (node:internal/process/pre_execution:336:27)
      at getItemsFromUrl (file:///app/src/jackett/index.js:9:20)
      at jackettSearch (file:///app/src/jackett/index.js:31:21)
      at file:///app/src/routes.js:54:30
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 'ERR_INVALID_URL',
    input: '192.168.0.168:9117/api/v2.0/indexers/all/results/torznab/api?apikey=woszse76vlgiumuwf1bj8uhevtocy00z&cat=2000&q=Oppenheimer'
  }
}
TypeError: Cannot read properties of null (reading 'rss')
    at file:///app/src/jackett/utils/processXML.js:17:26
    at Parser.<anonymous> (/app/node_modules/xml2js/lib/parser.js:318:18)
    at Parser.emit (node:events:519:28)
    at exports.Parser.Parser.parseString (/app/node_modules/xml2js/lib/parser.js:328:16)
    at Parser.parseString (/app/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/app/node_modules/xml2js/lib/parser.js:383:19)
    at file:///app/src/jackett/utils/processXML.js:5:10
    at new Promise (<anonymous>)
    at processXML (file:///app/src/jackett/utils/processXML.js:4:9)
Movie request. ID: tt15398776 Name: Oppenheimer
    at getItemsFromUrl (file:///app/src/jackett/index.js:11:22)
Searching on Jackett...
Will return Debrid link.
Series request. ID: tt1409055 Name: "Dragon Ball Z Kai" Season: 01 Episode: 01
Searching on Jackett...
Will return Debrid link.
TypeError: Cannot read properties of null (reading 'rss')
    at file:///app/src/jackett/utils/processXML.js:17:26
    at Parser.<anonymous> (/app/node_modules/xml2js/lib/parser.js:318:18)
    at Parser.emit (node:events:519:28)
    at exports.Parser.Parser.parseString (/app/node_modules/xml2js/lib/parser.js:328:16)
    at Parser.parseString (/app/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/app/node_modules/xml2js/lib/parser.js:383:19)
    at file:///app/src/jackett/utils/processXML.js:5:10
    at new Promise (<anonymous>)
    at processXML (file:///app/src/jackett/utils/processXML.js:4:9)
    at getItemsFromUrl (file:///app/src/jackett/index.js:11:22)
Series request. ID: tt1409055 Name: "Dragon Ball Z Kai" Season: 01 Episode: 01
Searching on Jackett...
Will return Debrid link.
TypeError: Cannot read properties of null (reading 'rss')
    at file:///app/src/jackett/utils/processXML.js:17:26
    at Parser.<anonymous> (/app/node_modules/xml2js/lib/parser.js:318:18)
    at Parser.emit (node:events:519:28)
    at exports.Parser.Parser.parseString (/app/node_modules/xml2js/lib/parser.js:328:16)
    at Parser.parseString (/app/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/app/node_modules/xml2js/lib/parser.js:383:19)
    at file:///app/src/jackett/utils/processXML.js:5:10
    at new Promise (<anonymous>)
    at processXML (file:///app/src/jackett/utils/processXML.js:4:9)
    at getItemsFromUrl (file:///app/src/jackett/index.js:11:22)
Series request. ID: tt1409055 Name: "Dragon Ball Z Kai" Season: 01 Episode: 01
Searching on Jackett...
Will return Debrid link.
Magnet added to RD. ID: undefined
Setting episode file for season/episode...
Selecting biggest file for season/episode...
TypeError: Cannot read properties of undefined (reading 'find')
    at selectBiggestFileSeason (file:///app/src/helpers/selectBiggestFileSeason.js:2:15)
    at setMovieFileRD (file:///app/src/helpers/getMovieRDLink.js:40:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getMovieRDLink (file:///app/src/helpers/getMovieRDLink.js:67:3)
    at async jackettSearch (file:///app/src/jackett/index.js:97:18)
    at async file:///app/src/routes.js:66:24
Movie request. ID: tt15398776 Name: Oppenheimer
Searching on Jackett...
Will return Debrid link.
Getting torrent info...
Torrent info: Oppenheimer.2023.1080p.BluRay.DD5.1.x264-GalaxyRG
Getting RD link...
Magnet added to RD. ID: undefined
Setting movie file...
TypeError: Cannot read properties of undefined (reading 'reduce')
    at setMovieFileRD (file:///app/src/helpers/getMovieRDLink.js:43:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getMovieRDLink (file:///app/src/helpers/getMovieRDLink.js:70:3)
    at async jackettSearch (file:///app/src/jackett/index.js:45:27)
    at async file:///app/src/routes.js:54:24

> stremio-addon-jackett@1.0.0 start
> node src/index.js

Server is running at http://localhost:3000
Movie request. ID: tt15398776 Name: Oppenheimer
Searching on Jackett...
Will return Debrid link.
Getting torrent info...
Torrent info: Oppenheimer.2023.1080p.BluRay.DD5.1.x264-GalaxyRG
Getting RD link...
Magnet added to RD. ID: undefined
Setting movie file...
TypeError: Cannot read properties of undefined (reading 'reduce')
    at setMovieFileRD (file:///app/src/helpers/getMovieRDLink.js:43:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getMovieRDLink (file:///app/src/helpers/getMovieRDLink.js:70:3)
    at async jackettSearch (file:///app/src/jackett/index.js:45:27)
    at async file:///app/src/routes.js:54:24

```

**Comment by aymene69** [comment]
Are you sure you've put the correct RD api key ?

**Comment by mckenna654** [comment]
Yes,

Still the same issues.

<img width="1139" alt="image" src="https://github.com/aymene69/stremio-jackett/assets/10954027/3647c881-fab8-4ca6-9b24-481b1ce3edfa">


Has anyone reported it working?
