### ISSUE TITLE
Error connection

### ISSUE THREAD

**Issue by ridgegate** [aymene69/stremio-jackett#26]
```
2024-01-25 17:53:42 TypeError: fetch failed
2024-01-25 17:53:42     at node:internal/deps/undici/undici:12442:11
2024-01-25 17:53:42     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-01-25 17:53:42     at async getItemsFromUrl (file:///app/src/jackett/utils/jackettSearch.js:11:14)
2024-01-25 17:53:42     at async jackettSearch (file:///app/src/jackett/utils/jackettSearch.js:33:15)
2024-01-25 17:53:42     at async fetchResults (file:///app/src/jackett/index.js:5:16)
2024-01-25 17:53:42     at async file:///app/src/routes.js:77:24 {
2024-01-25 17:53:42   cause: Error: connect ECONNREFUSED 127.0.0.1:9117
2024-01-25 17:53:42       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1602:16) {
2024-01-25 17:53:42     errno: -111,
2024-01-25 17:53:42     code: 'ECONNREFUSED',
2024-01-25 17:53:42     syscall: 'connect',
2024-01-25 17:53:42     address: '127.0.0.1',
2024-01-25 17:53:42     port: 9117
2024-01-25 17:53:42   }
2024-01-25 17:53:42 }
```

Is this addon on able to run properly with docker Jackett? I have installed Jackett on Win11 and tested with Jackett UI + Flaresolverr. THe UI gave me results but it is giving no source with above log. Anything I can do to resolve this issue? Thanks

**Comment by aymene69** [comment]
Jackett is unreachable

**Comment by ridgegate** [comment]
Thanks for your response. I see that it seems to be unreachable but I don't know how to make it reachable because it is working by itself and the web ui for jackett does work. I also did not set password to jackett and was able to have jackett using flaresolverr to reach 1377x. This should mean that jackett is working and reachable... 

Anything ideas? I will do some more investigation also

**Comment by aymene69** [comment]
Open ports in windows' firewall

**Comment by aymene69** [comment]
check issue #27
