### ISSUE TITLE
[Bug] Error in torrent search when it doesn't find a result using season+episode (One Piece)

### ISSUE THREAD

**Issue by hyoretsu** [aymene69/stremio-jackett#59]
```
0|stremio-jackett  | TypeError: files.filter is not a function
0|stremio-jackett  |     at selectBiggestFileSeasonTorrent (file:///srv/stremio-jackett/src/helpers/selectBiggestFileSeasonTorrent.js:2:30)
0|stremio-jackett  |     at jackettSearch (file:///srv/stremio-jackett/src/jackett/utils/jackettSearch.js:368:6)
0|stremio-jackett  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|stremio-jackett  |     at async fetchResults (file:///srv/stremio-jackett/src/jackett/index.js:12:16)
0|stremio-jackett  |     at async file:///srv/stremio-jackett/src/routes.js:97:24
```

**Comment by 9acca9** [comment]
```
> stremio-addon-jackett@1.3.4 start
> node dist/index.cjs

Server is running at http://localhost:3000
TypeError: Cannot read properties of undefined (reading '0')
    at getName (/home/panchines/stremio-jackett/dist/index.cjs:102:6592)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/panchines/stremio-jackett/dist/index.cjs:130:3276

```

**Comment by 9acca9** [comment]
```
> stremio-addon-jackett@1.3.5 start
> node dist/index.cjs

Server is running at http://localhost:3000
TypeError: Cannot read properties of undefined (reading '0')
    at getName (/home/panchines/stremio-jackett/dist/index.cjs:102:6592)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/panchines/stremio-jackett/dist/index.cjs:130:3276
```

This is helping? Or better i dont put nothing more and wait? (im just uploading here because maybe this help). If not, please let me know.
Thanks.

**Comment by 9acca9** [comment]
```
> stremio-addon-jackett@1.3.5 start
> node dist/index.cjs

Server is running at http://localhost:3000
TypeError: Cannot read properties of undefined (reading '0')
    at getName (/home/panchines/stremio-jackett/dist/index.cjs:102:6592)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/panchines/stremio-jackett/dist/index.cjs:130:3332

```

**Comment by aymene69** [comment]
please stop spamming

**Comment by 9acca9** [comment]
> please stop spamming

so, sorry, though that this was helping. Soorrrrrrrrrry!!!!!

**Comment by aymene69** [comment]
Fixed
