### ISSUE TITLE
[Bug] Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by 9acca9** [aymene69/stremio-jackett#62]
Just update, not working for me:
```
    ~/stremio-jackett    main !1  npm start                                                             ✔  panchines@manjaro 

> stremio-addon-jackett@1.3.2 start
> node dist/index.cjs

Server is running at http://localhost:3000
TypeError: Cannot read properties of undefined (reading '0')
    at getName (/home/panchines/stremio-jackett/dist/index.cjs:102:6592)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/panchines/stremio-jackett/dist/index.cjs:130:3292

```

**Comment by aymene69** [comment]
Update released

**Comment by 9acca9** [comment]
thanks but still not working
```
> stremio-addon-jackett@1.3.3 start
> node dist/index.cjs

Server is running at http://localhost:3000
TypeError: Cannot read properties of undefined (reading '0')
    at getName (/home/panchines/stremio-jackett/dist/index.cjs:102:6693)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/panchines/stremio-jackett/dist/index.cjs:130:3293
```

**Comment by hyoretsu** [comment]
Duplicate of #59
