### ISSUE TITLE
[Bug] TypeError: Cannot set properties of undefined (setting 'seeders')

### ISSUE THREAD

**Issue by 9acca9** [aymene69/stremio-jackett#77]
Using the last version im getting this:
```
TypeError: Cannot set properties of undefined (setting 'seeders')
    at jackettSearch (/home/panchines/stremio-jackett/dist/addon/index.cjs:102:10581)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchResults (/home/panchines/stremio-jackett/dist/addon/index.cjs:130:328)
    at async /home/panchines/stremio-jackett/dist/addon/index.cjs:132:79
```
Thanks

**Comment by aymene69** [comment]
Reopen an issue and follow the template

**Comment by 9acca9** [comment]
Thanks, here i reopen following the template.
https://github.com/aymene69/stremio-jackett/issues/82
