### ISSUE TITLE
[Bug] Cannot read properties of undefined (reading 'reduce')

### ISSUE THREAD

**Issue by andronedev** [aymene69/stremio-jackett#97]
**Describe the bug**
```shell
0|stremio      | TypeError: Cannot read properties of undefined (reading 'reduce')
0|stremio      |     at setMovieFileRD (/root/stremio-jackett/dist/index.cjs:100:9646)
0|stremio      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|stremio      |     at async getMovieRDLink (/root/stremio-jackett/dist/index.cjs:100:10174)
0|stremio      |     at async /root/stremio-jackett/dist/index.cjs:130:2514
0|stremio      | Node.js v20.11.0
```

**To Reproduce**
launch movie with RD

**Expected behavior**
work

**Screenshots**

**Your system info (please complete the following information):**
 - OS: [e.g. Ubuntu] -> 
 ```shell
 root@ubuntu:~/stremio-jackett# uname -a
Linux ubuntu 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
``` 
 - Version [e.g. 22] -> node v20.11.0
 - Docker or Node ? -> Node
 - Realdebrid? Torrent? -> Real Debrid

**Comment by andronedev** [comment]
I found the solution, just needed to reconfigure the addon as new properties were added with the updates!
